export enum PermissionResource {
    USER = 'USER',
    ORGANIZATION = 'ORGANIZATION',
    ORGANIZATION_MEMBERSHIP = 'ORGANIZATION_MEMBERSHIP',
    ROLE = 'ROLE',
    PERMISSION = 'PERMISSION',
    POLICY = 'POLICY',
    SESSION = 'SESSION',
    ACCOUNT = 'ACCOUNT',
    AUDIT_LOG = 'AUDIT_LOG',
}
