export enum PermissionResource {
    // Resources
    ACTIVE_ORGANIZATION = 'ACTIVE_ORGANIZATION',
    ORGANIZATION_MEMBERSHIP = 'ORGANIZATION_MEMBERSHIP',

    ORGANIZATION_ROLES = 'ORGANIZATION_ROLES',
    ROLE_MEMBERSHIPS = 'ROLE_MEMBERSHIPS',
    ROLE_PERMISSIONS = 'ROLE_PERMISSIONS',
    PERMISSIONS = 'PERMISSIONS',

    ACCESS_AUDIT_LOGS = 'ACCESS_AUDIT_LOGS',

    // Global resources
}
